In [1]:
import numpy as np
import pandas as pd

In [2]:
# when we combine multiple series that become dataframe

#### Creating a DataFrame

In [7]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [8]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)

In [10]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [11]:
# lets give a column to our list, as there is no column name in our llist
df2 = pd.DataFrame(data_list)
columns = ["Name", 'Age', "City", "Salary"]
df2 = pd.DataFrame(data_list, columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# we can create a datafrom from the list and dictionary

#### Selection and Indexing of Columns

In [12]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [14]:
df2['Name'] # targeting one column

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [15]:
df2["City"] # targeting one column or will get one column : city

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [135]:
df2[["Name", "City"]] # targeting two column : name and city

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [24]:
df2[["Name", "City", "Age"]] # targeting two column : name, city and Age

    Name      City  Age
0   John  New York   28
1   Anna     Paris   34
2  Peter    Berlin   29
3  Linda    London   42

#### Creating a new column

In [129]:
df2["Designation"] = ["Doctor", "Eng", "Doctor", "Eng"]

In [130]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000         Eng

#### Removing Columns

In [131]:
df2.drop('Designation', axis= 1) # here Designation will not delete, just will drop for this time, but in df2 Desigation is there

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [132]:
df2.drop("Designation", axis= 1, inplace= True) # Now Desigation will delete from our dataframe df2

In [41]:
df2.drop(["City", "Salary"], axis= 1) # we can delete 2 column at once as well, with help of inplace = True

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [42]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [133]:
df2.drop(0, axis= 0) # with axis 0 we can drop the row as well, with help of inplace = True we can drop that row forever

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [134]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selecting Rows

In [47]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [49]:
df2.loc[0] # with help of loc we can get row as well

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [51]:
df2.loc[[0, 1]] # we can get multiple row values also

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [60]:
df2.loc[[2, 0]] # we can get multiple row values also

    Name  Age      City  Salary
2  Peter   29    Berlin   62000
0   John   28  New York   65000

In [62]:
df2.iloc[0] # will get row index 0

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [64]:
df2.iloc[3] # will get row index 3

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

#### Selecting Subsets of Rows and Columns

In [65]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [70]:
df.loc[[0, 1]][["City", "Salary"]] # when we want to get suset of dataframe.

       City  Salary
0  New York   65000
1     Paris   70000

In [73]:
df.loc[[0, 1],["City", "Salary"]] # when we want to get suset of dataframe. better one, go eith this

       City  Salary
0  New York   65000
1     Paris   70000

In [79]:
df2.loc[[0, 3],["Age", 'Name', "City"]]

   Age   Name      City
0   28   John  New York
3   42  Linda    London

In [83]:
df2.loc[[2, 3], ["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

#### Conditional Selection

In [84]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [93]:
# i only want to see those people whose age is above 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [96]:
df2[df2["Salary"] > 65000] # show those whose salary is more than 65000

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

#### AND

In [111]:
# i only want people whose age is above 30 and their city must be paris
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

In [122]:
# get the people whose age is more than 30 and salary is more than 70000
df2[(df2["Age"] > 30) & (df2["Salary"] > 70000)]

    Name  Age    City  Salary
3  Linda   42  London   85000

#### OR

In [110]:
# i only want people whose age is above 30 or their city can be paris
df2[(df2["Age"] > 30) | (df2["City"] == "Paris")]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [123]:
# get the people whose age is more than 30 or salary is more than 70000
df2[(df2["Age"] > 30) | (df2["Salary"] > 70000)]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000