In [76]:
import numpy as np
import pandas as pd

#### Finding Missing Data

In [77]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [78]:
df.isna() # fird the null value from the df in form of true and false

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [79]:
df.isna().sum() # find how many null values are there in every column

A    1
B    0
C    2
D    3
dtype: int64

In [81]:
df.isna().any() # is there any column where there is no any missing values or null value(null values = False)

A     True
B    False
C     True
D     True
dtype: bool

#### Removing Missing Data

In [75]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [52]:
# we can perform removing null operation only on row level

In [36]:
df.dropna() # will drop all those row where there is null value in that row

     A  B    C    D
0  1.0  1  1.0  1.0

In [37]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [39]:
df.dropna(thresh=3) # will get those row who has more than 3 non null values(at least 3 null values should be there, that will be there in our df)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [41]:
df.dropna(thresh=4) # will get those rows who has more than 4 non null values

     A  B    C    D
0  1.0  1  1.0  1.0

In [44]:
df.dropna(thresh=5)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [45]:
df.dropna(thresh=1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

#### Filling the missing Data

In [46]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [67]:
# fill all the missing values with zero # fill works on column wise and drop work on row wise
df.fillna(0) # there will be no any change in our main df, for that we have to use inplace = True

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [68]:
df # check main df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [70]:
# fill the all different values for each column(for all null values)
values = {"A": 0, "B": 100, "C": 300, "D": 400}
df.fillna(value= values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [71]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [82]:
# we can fill with mean or avg value of that column in our df in place of null values (here fill.na(.mean()) will work on column waise)
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0